- xivo_test_helpers/mock.py
This pull request adds a matcher similar to mock.ANY that will match any valid UUID
ANY_UUID == 'foobar' => False
ANY_UUID == '97b72e89-b941-465b-a861-2178e8aa3f8a' => True
I've been adding code similar to this in almost every service I've been working on in the last few months
> mock: add a matcher for ANY valid UUID

- contribs/docker/wazo-auth-mock/wazo-auth-mock.py
POST /0.1/tenant must return the same information as GET
> wazo-auth-mock: POST /0.1/tenant must return all infos

- xivo_test_helpers/auth.py
1c8af6353134ea527d682edec52750ac889ae0db have make metadata[uuid]
mandatory on the mocked server. We should do the same for the client side.
> MockUserToken always set metadata[uuid]

- xivo_test_helpers/hamcrest/raises.py
reason: is_callable was a compatibility layer for python 3.0 until 3.2
Since hamcrest doesn't support these versions anymore, this helper
doesn't exist anymore.
> raises: remove usage of is_callable

- xivo_test_helpers/asset_launching_test_case.py
reason: amqp is too verbose with heartbeat
stevedore: too verbose each time we initialize client
> silence amqp/stevedore loggers by default

- contribs/docker/wazo-auth-mock/wazo-auth-mock.py
Why:
* When a daemon is missing required_acl decorator, it will validate the
token without scope.
* In this case, the wazo-auth mock should behave like wazo-auth and
return 204.
* It should only return 403 when the client asks for a scope.
> wazo-auth-mock: return 204 when validating wrong acl token without scope

- contribs/docker/wazo-auth-mock/wazo-auth-mock.py
Why:
* wazo-provd integration tests are failing because wazo-auth doesn't
raise an exception
* Token should only be valid for visible tenants
> HEAD /token: check tenant is visible

- xivo_test_helpers/db.py
Why:
* With too many fixtures, there is an error "sorry, too many clients
already"
> db: avoid instanciating a new DB engine for each fixture

- xivo_test_helpers/asset_launching_test_case.py
Remove annoying deprecated warning
```
--no-ansi option is deprecated and will be removed in future versions.
```
Warning: it will probably fail in all environment without the last docker-compose version
Post-merge: inform all devs
> stop to use deprecated --no-ansi option with docker-compose

- xivo_test_helpers/asset_launching_test_case.py
reason: wazo-call-logd-migrate-db need to know returncode from the
command
> allow to specify attribute returned on docker_exec

- xivo_test_helpers/hamcrest/raises.py
Why:
* Easier to find the source of the error
> raises: show the traceback of the actual error

- xivo_test_helpers/asset_launching_test_case.py
Why:
* Needed to sync files across containers, e.g. setupd
> asset-launching-test-case: allow copying files across containers

- contribs/docker/wazo-amid-mock/mock-wazo-amid.py
- contribs/docker/wazo-auth-mock/wazo-auth-mock.py
- contribs/docker/wazo-confd-mock/mock-wazo-confd.py
- contribs/docker/wazo-sysconfd-mock/wazo-sysconfd-mock.py
Why:
* When receiving many requests, the list of requests stored can take a
lot of memory.
How:
* Set a maximum size to the list of request via deque()
> service mocks: limit memory size

- xivo_test_helpers/asset_launching_test_case.py
Why:
* wazo-confd integration tests are failing with memory error when
getting the container id
> asset launching: reduce timeout

- xivo_test_helpers/asset_launching_test_case.py
Why:
* 1 second is too short and makes correct tests fail
> asset launching: increase timeout for container ID

- xivo_test_helpers/asset_launching_test_case.py
Why:
* In wazo-confd, container logs amount to 250M
* There is no gain to store the logs in memory
* So just dump them in a file
Why:
* It can cause false-positives in tests: sometimes the docker-compose
commands are longer
* It was only introduced to prevent against a too big output that does
not happen
> Pull request for reduce-dump-logs-memory

- wazo_test_helpers/asset_launching_test_case.py
why: docker-compose v2 will fail if image is not on docker hub
why: because according the documentation
basicConfig: This function does nothing if the root logger already has
handlers configured for it.
Some module already have logger configured before calling this
library
> Pull request for WAZO-2658-docker-compose-v2

- wazo_test_helpers/bus.py
Why:
* With some consumers listening on wazo-headers,
integration test fails because that exchange does not
exist in test environments.
This change addresses the need by:
* Helps transitioning to using a headers-base exchange
instead of routing keys
> WAZO-2660 Ability to add downstream exchange to bus helper

- wazo_test_helpers/until.py
Why:
* The error is more visible in the exception message than in debug
logger.
> Pull request for until-return-raise-errors

- wazo_test_helpers/asset_launching_test_case.py
Why:
* Allows running different assets in the same time.
* It's useful when using pytest fixtures that are only teardown after
all the tests have finished running
> asset launching test case: separate assets in docker-compose

- contribs/docker/flask/Dockerfile
apt update/upgrade is not needed, as the base image
is not locked to a specific version of Python.
> Clean the Dockerfile for the flask image

- contribs/docker/wazo-auth-mock/wazo-auth-mock.py
Fix 500 error when trying to delete a user who does not exist:
```
INFO:werkzeug:172.26.0.3 - - [30/Nov/2022 14:22:05] "DELETE /0.1/users/xxxxxxxxxxxxxxxxxxxxx HTTP/1.1" 500 -
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2309, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2295, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1741, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in …
```
> Fix 500 when deleting non-existing user

- contribs/docker/wazo-auth-mock/wazo-auth-mock.py
- wazo_test_helpers/auth.py
Why:
* Needed by the teams plugin to fetch list of connected users with external service
> WAZO-2943: add `external users` command to mock and client

- wazo_test_helpers/asset_launching_test_case.py
Why:
* When a container is down, docker-compose would fail with error "No
such service: wazo-..."
> asset_launching_test_case: fix docker-compose status

- setup.py
why: new requests version (2.30) which include urllib3 v2, include
breaking change that impact docker library
> tests: pin requests version to avoid breaking docker lib

- contribs/docker/wazo-sysconfd-mock/wazo-sysconfd-mock.py
reason: This is universal and debian and python images have different locations
> Use /usr/bin/env python3 and not local

- .pre-commit-config.yaml
- contribs/docker/wazo-amid-mock/mock-wazo-amid.py
- contribs/docker/wazo-auth-mock/wazo-auth-mock.py
- contribs/docker/wazo-confd-mock/mock-wazo-confd.py
- contribs/docker/wazo-sysconfd-mock/wazo-sysconfd-mock.py
- pyproject.toml
- setup.py
- tox.ini
- wazo_test_helpers/asset_launching_test_case.py
- wazo_test_helpers/auth.py
- wazo_test_helpers/bus.py
- wazo_test_helpers/db.py
- wazo_test_helpers/filesystem.py
- wazo_test_helpers/hamcrest/has_callable.py
- wazo_test_helpers/hamcrest/raises.py
- wazo_test_helpers/hamcrest/uuid_.py
- wazo_test_helpers/mock.py
- wazo_test_helpers/wait_strategy.py
- zuul.yaml
why: used by wazo-websocketd for dynamic auth check strategy
why: mostly used to dynamically generate configuration on service
note: we use cat instead of echo to write file to allow to have carriage
return
> Pull request for WAZO-3225-dynamic-token-check

- contribs/docker/wazo-auth-mock/wazo-auth-mock.py
an expired token does not return a payload since it does not exists anymore
> auth mock: fix GET on expired token

- contribs/docker/wazo-confd-mock/mock-wazo-confd.py
Why:
* wazo-calld relies on 404 behavior when getting a user in the wrong
tenant
> confd mock: filter users by tenant

- wazo_test_helpers/asset_launching_test_case.py
Why:
* Some log lines appear at unpredictable times and may affect assertions
> asset l. testcase: allow excluding logs when counting

- wazo_test_helpers/asset_launching_test_case.py
Why:
* Can analyze logs with dedicated tools in a container
> asset l. test case: allow running one-shot container

- contribs/docker/wazo-confd-mock/mock-wazo-confd.py
Also, fix recurse logic for moh route
Why: request.args.get('...') always returns a string, thus  will always
be True.
> WP-1612: add recurse to contexts route
